### PR TITLE
Update to qmlweb-parser 0.3.0

### PR DESCRIPTION
**Pull request by stephenmdangelo**

### CODE REVIEW

**Comment by ChALkeR** [comment]
Note that this would make ~~qmlweb-parser~~ gulp-qmlweb `master` branch incompatible with qmlweb 0.1, but compatible with qmlweb 0.2 (and the current `master` branch).

**Comment by stephenmdangelo** [comment]
> Note that this would make qmlweb-parser master branch...

@ChALkeR You mean the gulp-qmlweb `master` branch, yes?

**Comment by ChALkeR** [comment]
@stephenmdangelo Ah, yes, thanks, that was a mistype. Fixed.

**Comment by Plaristote** [comment]
Well, this change is mandatory for gulp-qmlweb to work with current versions of qmlweb. I'll be merging this. We might also want to move the version number up, right ?
We currently can't bring up a working version of gulp-qmlweb from the npm repository.

**Pull request merged**
